version: '3'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'True'
      TZ: 'America/New_York'
    volumes:
      - ~/.docker/mysql:/var/lib/mysql
  app:
    build: .
    environment:
      MYSQL_HOST: 'db'
      MYSQL_PORT: '3306'
      TZ: 'America/New_York'
    volumes:
      - .:/app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
