development: &default
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  host: <%= ENV.fetch('MYSQL_HOST', 'localhost') %>
  port: <%= ENV.fetch('MYSQL_PORT', '3306') %>
  username: root
  database: training_development

test:
  <<: *default
  database: training_test
