development: &default
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  username: root
  database: training_development

test:
  <<: *default
  database: training_test
  username: travis
